version: "0001--11-Sep-2022"
author: "Raniaarn"
title: "OS222: Operating Systems 2022-2"
githublink: "https://github.com/raniaarn/os222"
githubpagelink: "https://raniaarn.github.io/os222/"
tblink: "https://os.vlsm.org/Log/raniaarn.tar.bz2.txt"
myloglink: "/TXT/mylog.txt"
encoding: "UTF-8"
github: [metadata]
